select * from customer

--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_revenue 
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied='Yes'
and 
purchase_amount>=(select avg(purchase_amount)from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as avg_reveiew_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5


--Q4. Compare the average purchase amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount::numeric),2) as avg_amount
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg_amount desc


--Q5. Do subscribed customers spend more? Compare average spend and total revenue between 
--subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customer,
round(avg(purchase_amount::numeric),2)as average_spend,
round(sum(purchase_amount::numeric),2) as total_revenue
from customer
group by subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
100*sum(case when discount_applied='Yes'
		then 1 
		else 0 
		end)/count(*) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number 
--of previous purchases, and show the count of each segment.

with customer_type as(
select customer_id, previous_purchases,
case when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
	from customer
)

select customer_segment, count(*) as number_of_cust
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?


with item_count as (
select category, item_purchased, count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as rnk
from customer
group by category, item_purchased
)

select rnk,category, item_purchased,total_orders from item_count
where rnk>=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc

--Q11. Identify products that have high purchase counts but relatively low average review ratings. 

WITH product_stats AS(
SELECT item_purchased, 
COUNT(*) AS total_purchases, 
AVG(review_rating::numeric) AS avg_rating FROM customer GROUP BY item_purchased ), 
overall_avg AS ( SELECT AVG(total_purchases) AS avg_purchases, 
AVG(avg_rating) AS avg_rating_overall FROM product_stats ) 

SELECT p.item_purchased, 
p.total_purchases, 
ROUND(p.avg_rating,2) AS avg_rating 
FROM product_stats p 
JOIN overall_avg o 
ON 1=1 
WHERE p.total_purchases > o.avg_purchases 
AND 
p.avg_rating < o.avg_rating_overall 
ORDER BY p.total_purchases DESC;